# Generated by Django 5.1.3 on 2024-11-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringtones', '0002_alter_ringtone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringtone',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ringtone',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
