# Generated by Django 5.1.3 on 2024-11-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringtones', '0003_ringtone_likes_ringtone_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ringtone',
            name='tags',
        ),
        migrations.AddField(
            model_name='ringtone',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ringtones.tag'),
        ),
    ]
