# Generated by Django 5.1.3 on 2024-11-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringtones', '0004_tag_remove_ringtone_tags_ringtone_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ringtone',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='ringtone',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
