# Generated by Django 5.1.2 on 2024-12-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringtones', '0006_remove_ringtone_likes_ringtone_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringtone',
            name='genre',
            field=models.CharField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hiphop', 'Hip-hop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('instrumental', 'Instrumental'), ('bgm', 'Bgm'), ('remix', 'Remix'), ('slowed', 'Slowed'), ('lofi', 'Lofi'), ('indie', 'Indie'), ('k-pop', 'K-pop'), ('rnb', 'Rnb'), ('others', 'Others')], max_length=50),
        ),
    ]
